#!/data/data/com.termux/files/usr/bin/bash

pkg update -y && pkg upgrade -y
pkg install -y wget nano libjansson

mkdir -p ~/ccminer && cd ~/ccminer

wget https://raw.githubusercontent.com/Darktron/pre-compiled/generic/ccminer
wget https://raw.githubusercontent.com/Darktron/pre-compiled/generic/start.sh

chmod +x ccminer start.sh

cat > config.json << 'EOF'
{
    "pools":
        [{
            "name": "AP-LUCKPOOL",
            "url": "stratum+tcp://ap.luckpool.net:3956",
            "timeout": 180,
            "disabled": 0
        }],
    "user": "RMyGreKXJaRFtWwE2AeFhLK9dNfxW2SHhn.Donans",
    "pass": "hybrid",
    "algo": "verus",
    "threads": 8
}
EOF

bash ~/ccminer/start.sh
